#!/usr/bin/env python3

import random

# число элементов в списке, влияет на потребляемую память
n = 400 * 1000 * 1000

# число итераций замены элементов списка
c = 10

print('Наполняем список (n = {}) случайными числами...'.format(n))

try:
    # добавляем в пустой список n случайных чисел
    x = []
    for _ in range(n):
        x.append(random.random())

    for i in range(c):
        print('Читение и запись новых значений, итерация {} из {}'.format(i + 1, c))

        # заменяем элементы списка на новые
        for i in range(n):
            x[i] = x[i] * 0.999

    del x

except KeyboardInterrupt:
    del x

