#!/usr/bin/env python3

from signal import signal, SIGTERM

def signal_handler(signum, frame):
    print('Got signal {}'.format(signum))

signal(SIGTERM, signal_handler)

rate = 99999

x = []

while True:
    x.append('#' * rate)

# http://okturing.com/src/6140/body
