.TH nohang 1
.SH NAME
nohang \- no hang daemon

.SH SYNOPSIS
.B nohang
.RB [ OPTION ]...

.SH DESCRIPTION
Nohang is a highly configurable daemon for Linux which is able to correctly prevent out of memory (OOM) and keep system responsiveness in low memory conditions.

.SH HOW TO CONFIGURE
Just edit the config /etc/nohang/nohang.conf and restart the daemon.

.SH SEE ALSO
https://github.com/hakavlad/nohang
