.TH nohang 1
.SH NAME
nohang \- no hang daemon

.SH SYNOPSIS
.B nohang
.RB [ OPTION ]...

.SH DESCRIPTION
Nohang - аналог earlyoom с поддержкой zram и SIGTERM. При дефиците доступной памяти nohang корректно завершает наиболее прожорливые процессы сигналом SIGTERM, тем самым препятствуя зависанию, а также избыточному убийству процессов ядерным OOM killer'ом. See https://github.com/hakavlad/nohang

.SH OPTIONS
.TP
.BI \-c " CONFIG",
.BI \-\-config " CONFIG"
path to the config file, default values:
.I ./nohang.conf,
.I /etc/nohang/nohang.conf
.TP
.BI \-h,
.BI \-\-help
show help message and exit
